version: "3.3"
services:
  application:
    build:
      context: .
    image: gazin/app
    container_name: app-gazin
    volumes:
      - ./:/home/application
      - /home/application/node_modules
      - /home/application/packages/api/node_modules
      - /home/application/packages/web/node_modules
    ports:
      - "3000:3000"
      - "3333:3333"
    links:
      - postgres
    networks:
      - gazin-network
    depends_on:
      - "postgres"

  postgres:
    container_name: postgres-gazin
    image: postgres:10
    networks:
      - gazin-network
    environment:
      POSTGRES_PASSWORD: postgres
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - gazinpgdata:/var/lib/postgresql/data
      - ./.docker/postgres_scripts:/docker-entrypoint-initdb.d/
    ports:
      - 5551:5432

networks:
  gazin-network:
volumes:
  gazinpgdata:
